name: Test
on: pull_request
jobs:
  run-testcases:
    name: Plugin test cases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install all dependencies
        run: yarn

      - name: Run Jest Tests
        run: yarn run test
